### ISSUE TITLE
French Translation error

### ISSUE THREAD

**Issue by MajorTom327** [Futureglobe/SnipAway_IssueTracker#10]
**Is your feature request related to a problem?**
Somes french translations are not correct

**Describe the solution you'd like**
Change the translation

**Describe alternatives you've considered**

| Where                        | English                  | French                         | Fixed French                       | Note                                                                          |
| ---------------------------- | ------------------------ | ------------------------------ | ---------------------------------- | ----------------------------------------------------------------------------- |
| Toolbar                      | View                     | Vue                            | Affichage                          |                                                                               |
| Toolbar                      | Help                     | Aidez-Moi                      | Aide                               |                                                                               |
| Toolbar / SnipAway           | Exit                     | Sortie                         | Quitter                            |                                                                               |
| Toolbar / File               | Mark snippet as favorite | Mark snippet comme favori      | Marquer l'extrait comme favori     |                                                                               |
| Toobar / View                | Focus snippet            | Extrait de mise au point       |                                    | I don't know how to translate this, but currently it's mean "a part of focus" |
| Toolbar / Help               | Request Feature...       | Fonction de demande            | Demande de fonctionnalitée         |                                                                               |
| Settings / General / Theme   | Light                    | Lumière                        | Clair                              |                                                                               |
| Settings / General / Keep    | Leave open in background | Laisse ouverte en arrière-plan | Garder ouvert en arrière-plan      |                                                                               |
| Settings / Editor / Tab Size | Tab Size                 | Taille de l'onglet             | Taille de la tabulation            |                                                                               |
| Settings / Editor / Snippet  | Mark snippet as favorite | Mark snippet comme favori      | Marquer l'extrait comme favori     |                                                                               |
| Settings / Folders / Color   | Select Folder Color      | Sélectionner le dossier        | Sélectionner la couleur du dossier |                                                                               |
| Snipper / Unexpand           | Shrink Editor            | Réducteur de rétrécissement    | Réduire l'éditeur                  |                                                                               |

**Additional context**
N/A

**Comment by Futureglobe** [comment]
Hey @MajorTom327 ,

Thanks for your report.
We think it's great that you don't just mention the errors but also that you delivered new and correct translations directly. Thank you very much for that. Our team will correct the translations and release them with the next software update.

Thanks,
Your Futureglobe Support Team
