### ISSUE TITLE
php Snippet empty after restart

### ISSUE THREAD

**Issue by vaibhav011286** [Futureglobe/SnipAway_IssueTracker#11]
I pasted attached php file code in php snippet and after restart, my whole php snippet lost and when I checked the **.snipaway** file, its **0kb**.. now I am totally lost, as I had too many functions n codes saved in it and all gone at sudden! _How to recover? can you explain?_

[php.txt](https://github.com/Futureglobe/SnipAway_IssueTracker/files/3489316/php.txt)

**Comment by Futureglobe** [comment]
In our test environment we created the content of your attached PHP file as a snippet (see GIF)
After several restarts it was still there.
Possibly this is a problem with your filesystem or a problem with write or read permissions.
We are not aware of any problem with our saving functionality as it works for hundreds of users without any problems.

![PHPSnippetIssue](https://user-images.githubusercontent.com/27356972/62862192-ad361680-bd05-11e9-8806-e931234eef5c.gif)

**Comment by vaibhav011286** [comment]
I see you using mac but I am using window 10 latest and i already had php code saved in it n after pasting the same code and restart the app cleared the whole php snippet.. how this can happen? And what we do you meant by file system or permission because i already have codes in it.. and let's say if i had permission issue then why it cleared old code saved in it? It just should not make it blank!

**Comment by Futureglobe** [comment]
Hi @vaibhav011286 

Our code base for the mac is identical to the one on windows. But we also tested the same behavior on a test system with Windows and got the same result. Even if you add something to an existing snippet, nothing will be overwritten or emptied. It is impossible to delete snippet content by this process. We can't explain this behavior, as it works fine everywhere else. If you already had snippets created, there should be no problem with the filesystem. That was just a guess from us. We sorry that we cant help you with this.

Thanks,
Futureglobe Support Team

**Comment by vaibhav011286** [comment]
Yes I had around 1.5k lines of codes saved already.. so there must be something happened while writing the snippet when i pasted new code n writing/updating is done working the software so there must be something wrong/conflict in case while saving the snippets.. That's all I know that my saved codes are gone! ☹️

**Comment by Futureglobe** [comment]
Hi @vaibhav011286 

We're sorry about that... As already mentioned we do not know anything that can lead to problems. It must be something that's different with your system that sometimes causes a problem with SnipAway. What kind of setup do you have? Do you work with a virtual machine? Or do you have other deviations that most users don't have? According to our error logs we collect for analytics purposes, there is no problem registered by us. 

Thanks,
Futureglobe Support Team
