### ISSUE TITLE
portable version

### ISSUE THREAD

**Issue by romain1206** [Futureglobe/SnipAway_IssueTracker#21]
first of all thank you for your software

as I work on several PCs with a usb key it would be nice to have SnipAway in portable version.

it should be possible to store the database in the same folder as the SnipAway executable

thank you

**Comment by Futureglobe** [comment]
Hello @romain1206 ,

Thank you for your request.
You can set the default storage location of your snippets inside the general settings tab. 
This way you can store the "database" inside the root installation directory. 

We hope this helps you.

Your Futureglobe Support Team
