### ISSUE TITLE
Add option to open in browser Web Snippet and Zoom

### ISSUE THREAD

**Issue by jvaldiviezo9** [Futureglobe/SnipAway_IssueTracker#3]
**Is your feature request related to a problem?**
I see very small an blurry some documentation, for example the Pandas library of Python, there is a lot of data and seems a little bit blurry.

**Describe the solution you'd like**
Could be great to add a zoom option and/or the option to open in browser in a direct way. I think the best would be to include both.

**Describe alternatives you've considered**
I think an easy way to do a workaround instead to do a zoom would be to generate a live hyperlink that open that in a browser.

**Additional context**
![image](https://user-images.githubusercontent.com/18518204/56867837-0032ca80-69b0-11e9-8d17-2f585f0170ab.png)

**Comment by Futureglobe** [comment]
Hey @jvaldiviezo9,

Thank you for the feature request.
The hyperlink suggestion sound very nice, and we will take a look at it and implement it with the new update. Regarding the zoom feature we will also talk about this internally and implement this feature if we think it would be useful. Until the update is ready, you can use the shortcut "Alt+Cntrl+F" to make the website area go full screen. This maybe will solve the issue with the blur at least temporarily.

Does this sound good to you?

Thanks
Your Futureglobe Support Team

**Comment by jvaldiviezo9** [comment]
Yes, I've tried that, but its not so convenient. Anyways would be waiting for the next update! Thank you a lot!

**Comment by Futureglobe** [comment]
@jvaldiviezo9 Just to let you know, our team already implemented this feature. We added this new button which will show up when you open a web snippet.

![Unbenannt](https://user-images.githubusercontent.com/27356972/56946061-6bec7300-6b29-11e9-8807-3c28fc5062a1.PNG)

This way you can open the website directly in your system browser. It will be included in the next update 1.2.2.

Thanks for your contribution,
Your Futureglobe Support Team

**Comment by jvaldiviezo9** [comment]
Perfect, so I just need to wait for the auto update inside the app right?

**Comment by Futureglobe** [comment]
@jvaldiviezo9 If you have the option "Check for Update" set to "Always" SnipAway should automatically check for an update when its started. This way you get a notification when we release the new update.
We are also making some big improvements to the markdown system so this update will include other improvements to. But it shouldn't take to long for the update to be released.
Thanks,
Your Futureglobe Support Team

**Comment by Futureglobe** [comment]
Hey @jvaldiviezo9 for your information we just released version 1.2.2 you can install the update the next time you open SnipAway. Take a look at the changelogs and see the other things we changed:

https://snipaway.futureglobe.de/changelog.html#1_2_2

Thanks,
Your Futureglobe Support Team

**Comment by jvaldiviezo9** [comment]
Thank you so much! Will try it soon!

**Comment by Futureglobe** [comment]
Hey @jvaldiviezo9 just to let you know, 

we now also implemented your request regarding the separate zoom functionality.
It will be released with the next update. Here is a quick example of how its going to work:

![WebZoomFeature](https://user-images.githubusercontent.com/27356972/61373033-fdea5900-a898-11e9-9cdd-17f2bfb75623.gif)

We hope you like it. 

Your Futureglobe Team

**Comment by jvaldiviezo9** [comment]
Those are very great news!

By the way, do you know if it would be possible to do this via Ctrl + Scroll too?

**Comment by Futureglobe** [comment]
Hey @jvaldiviezo9 ,

it would be possible but we actively decided against a shortcut for this feature.
But if we decide to add it in the future we will update this issue.

Thanks,
Your Futureglobe Team
