### ISSUE TITLE
Zoom in the Code Editor

### ISSUE THREAD

**Issue by jvaldiviezo9** [Futureglobe/SnipAway_IssueTracker#4]
**Is your feature request related to a problem?**
I think could be amazing to implement zoom on the code editor, this allow to see clearly or even edit easily on the same snippet

**Describe the solution you'd like**
A shortcut as Ctrl + "+", or Crtl + Scroll to zoom in and zoom out

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by Futureglobe** [comment]
Hey @jvaldiviezo9,

Thank you for your feature request.
You can find the editor settings inside the app setting which you can access over the menu icon on the upper left corner. There you can set the "Font Size" of the editor. This should allow you to see the snippet code more clearly. Also, you can maximize the editor panel using the shortcut: "Alt+Cntrl+F".
Does this fix your issue or is a zoom feature needed even after changing the font size.
If so could yo provide a screenshot, so we can take a closer look at the problem.

Thanks,
Your Futureglobe Support Team

**Comment by jvaldiviezo9** [comment]
I figured out after that I could change that. Well in any case could be amazing to change the fonts size with a shortcut like the browser "Ctrl" + "+" for example or with Ctrl + Scroll and that this affects the entire Application.

**Comment by Futureglobe** [comment]
@jvaldiviezo9 we will look into this and speak about it. If our team thinks this will improve the overall application we will inlcude it with the next update. As of now we will close this issue. 
Thanks for your contribution.

Your Futureglobe Support Team
