### ISSUE TITLE
Folders in Folder

### ISSUE THREAD

**Issue by petrustia** [Futureglobe/SnipAway_IssueTracker#6]
It will be great to have folders in folder.
In fact, subfolders.

**Comment by Futureglobe** [comment]
Hey @petrustia thanks for your feature request.
I'm sorry to tell you that as of now we have no plans to support subfolders.
If our plans change, and we decide to add subfolder support we will let you know.

Thanks for your contribution.

Your Futureglobe Support Team

**Comment by petrustia** [comment]
Thanks !
