### ISSUE TITLE
code editing is not locked after editing settings

### ISSUE THREAD

**Issue by l0n3w0lf-01** [Futureglobe/SnipAway_IssueTracker#8]
**Describe the bug**
Please describe us the bug as precise as possible

**Steps to reproduce the bug**
if possible explain how to get the bug to occur

For example:
1. Click on Lock Editing 
2. Go to Settings and change any values
3. Hit Save
4. Type in the code editor. Code editing is no longer locked.

**Expected behavior**
code editing should be locked
![Capture](https://user-images.githubusercontent.com/31983432/61192794-a659bb00-a6e9-11e9-85e8-a117d1825fb6.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10 x64bit
 - Application Version : there's no version info avaiable

**Comment by Futureglobe** [comment]
Hey @l0n3w0lf-01 ,

thank you very much for reporting this small bug.
We have fixed the issue/bug and it will be released with the next update coming soon.

Thanks,
Your Futureglobe Support Team

**Comment by larrysolis** [comment]
thanks. :) can't wait for the release.

**Comment by Futureglobe** [comment]
Hey @larrysolis, 

We just wanted to let you know that we just released a new update.
With this update the bug should be fixed, let us know if everything is working again.

Thanks,
Your Futureglobe Support Team
