### ISSUE TITLE
Lost all my snippets while updating

### ISSUE THREAD

**Issue by vaibhav011286** [Futureglobe/SnipAway_IssueTracker#9]
Just updated the app, and voilla after restart, all my snippets gone... why you giving update when you dont ask user to save sinppets or save snippets while updating? total loss.. i had tons of snippets stored.. started loving your app, but at sudden, its totally disappointed..

**Comment by Futureglobe** [comment]
Hi @vaibhav011286,

we'd like to apologize for the problems. The update has no effect on your saved snippets.
SnipAway always saves your snippets locally on your computer in the defined storage path.
It could be that our app has overwritten your local storage path. But you can easily change this.
Under the menu in the upper left corner you can open the settings and switch to the General tab. Here you can change the Storage Folder Path using the pencil icon.
By default the Storage Folder Path is stored in your "Documents" folder.
So your snippets are somewhere on your hard drive, don't worry, they haven't been removed.
If you can't find your storage path, I would ask you to simply search your file explorer for ".snipaway". 
This is the file extension of the snippet files we store.

If you still need help, feel free to write us here or email us at support@futureglobe.de

Thanks
Your Futureglobe Support Team

**Comment by vaibhav011286** [comment]
Thanks... actually I stored all my snipps inside program dir!
